### ISSUE TITLE
Every gem < 0.4.0 yanked?! Breaks Rails' ActiveStorage

### ISSUE THREAD

**Issue by gr8bit** [minad/mimemagic#99] opened 2021-03-24 11:59 UTC
What happened here? Where are the versions < 0.4.0?
https://rubygems.org/gems/mimemagic/versions

ActiveStorage depends on it and can currently not be installed due to the yanking...
```
    activestorage (6.1.3)
      ...
      mimemagic (~> 0.3.2)
```

**Comment by tibra** [comment] 2021-03-24 12:01
I just wanted to open an issue on that one, too:
`bundle stderr: Your bundle is locked to mimemagic (0.3.5), but that version could not be found
in any of the sources listed in your Gemfile. If you haven't changed sources,
that means the author of mimemagic (0.3.5) has removed it. You'll need to update
your bundle to a version other than mimemagic (0.3.5) that hasn't been removed
in order to install.`

**Comment by morgoth** [comment] 2021-03-24 12:02
duplicate of https://github.com/minad/mimemagic/issues/98

**Closed** 2021-03-24 12:03 UTC
